version: "2"
services:
  namesrv:
    build:
      context: .
      target: vulnerable
    container_name: rmq-namesrv
    ports:
      - 9876:9876
    command: sh mqnamesrv

  broker:
    build:
      context: .
      target: vulnerable
    container_name: rmq-broker
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.9.4/conf/broker.conf

  poc:
    build:
      context: .
      target: poc
    container_name: rmq-poc
    links:
      - broker
    command: sleep inf
