services:
  xzbackdoor:
    container_name: xzbackdoor-vulnerable
    build:
      context: .
      target: vulnerable
    ports:
      - "2222:22"

  poc:
    container_name: xzbackdoor-poc
    build:
      context: .
      target: exploit
    links:
      - xzbackdoor
